apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arkiv-mock
  namespace: team-soknad
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8092
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://arkiv-mock.dev.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: soknadsarkiverer
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/dev/srvarkivmock

  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: APPLICATION_PROFILE
      value: dev
    - name: ISSO_WELL_KNOWN_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: ACCEPTEDAUDIENCE
      value: 7b9e459e-225f-4fa8-b79f-2a15b993dae8
    - name: EXPIRYTHRESHOLD
      value: "1"
