server:
  port: 8092

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev | docker

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token

kafkaconfig:
  secure: ${KAFKA_SECURITY}
  kafkaBrokers: ${KAFKA_BROKERS}
  truststorePath: ${KAFKA_TRUSTSTORE_PATH}
  keystorePath: ${KAFKA_KEYSTORE_PATH}
  credstorePassword: ${KAFKA_CREDSTORE_PASSWORD}

  entitiesTopic: ${KAFKA_ENTITIES_TOPIC:privat-soknadinnsending-systemtests-entities}
  numberOfCallsTopic: ${KAFKA_NUMBEROFCALLS_TOPIC:privat-soknadinnsending-systemtests-numberofcalls}


---
spring:
  config:
    activate:
      on-profile: test | default

no.nav.security.jwt:
  issuer:
    isso:
      discoveryurl: https://localhost/metadata
      accepted_audience: aud-localhost
      cookie_name: localhost-idtoken

kafkaconfig:
  secure: FALSE
  kafkaBrokers: localhost:29092
  truststorePath: path
  keystorePath: path
  credstorePassword: pass

  entitiesTopic: privat-soknadinnsending-systemtests-entities
  numberOfCallsTopic: privat-soknadinnsending-systemtests-numberofcalls
