name: Build

on: [push]

jobs:
  build:
    name: Build and push Docker container
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build with maven
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: mvn install --settings maven-settings.xml --file pom.xml
