name: Build, push, and deploy

on: [push]

permissions:
  id-token: "write"

jobs:
  build-and-push:
    name: Build and push Docker container
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build with maven
        run: mvn install --file pom.xml

      - name: Build and push Docker image
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-soknad
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          image_suffix: dev
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-loadtests:
    name: Deploy to loadtests
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yml,.nais/topics/config-systemtests-entities.yml,.nais/topics/config-systemtests-numberofcalls.yml
          VAR: image=${{needs.build-and-push.outputs.image}}
