name: Run end-to-end-tests on pull-requests

on:
  pull_request:

jobs:
  run-end-to-end-tests:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: 'Build the code for soknadsmottaker'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: soknadsmottaker
          skip_tests: true
          branch: feature/nologin-send-inn
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Build the code for soknadsarkiverer'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: soknadsarkiverer
          skip_tests: true
          branch: feature/nologin
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Build the code for innsending-api'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: innsending-api
          skip_tests: true
          branch: feature/uinnlogget-send-inn
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Build the code for arkiv-mock (this PR)'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: arkiv-mock
          skip_tests: true
          branch: feature/no-login
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Run the end-to-end-tests'
        uses: navikt/archiving-infrastructure/.github/checkout-and-build@main
        with:
          component_name: archiving-infrastructure
          sub_directory: system-tests
          branch: feature/no-login
          skip_tests: false
          run_docker_build: false
